name: 'HELfi Grant premade content'
type: module
core: 8.x
core_version_requirement: '^8 || ^9'
package: HELfi
dependencies:
  - default_content
default_content:
  menu_link_content:
    - ada20fc6-a716-42ff-9cc2-3dab6fe51dc3
  node:
    - 7f2574d3-d889-46d6-a716-7a05f2e2e761
    - 94868e26-669f-45fd-bba0-2ac3bad827b5
'interface translation project': grant_applications_content
'interface translation server pattern': modules/contrib/grant_applications_content/helfi_features/grant_applications_content/translations/%language.po
