name: Hel.fi Grant Applications
description: Subtheme for The Grant Applicaitons instance.
type: theme
base theme: hdbt
tags: sub-theme
core_version_requirement: ^8 || ^9
screenshot: helfi_grant_applications.png
'interface translation project': helfi-grant-applications
'interface translation server pattern': themes/custom/helfi_grant_applications/translations/%language.po

# Regions
regions:
  header_top: Header - Top
  header_branding: Header - Branding
  header_bottom: Header - Bottom
  messages: Messages
  breadcrumb: Breadcrumb
  tools: Tools
  before_content: Before content
  sidebar_first: First sidebar
  content: Content
  sidebar_second: Second sidebar
  after_content: After content
  footer_top: Footer - Top
  footer_bottom: Footer - Bottom
  attachments: Attachments


# Libraries
libraries:
  - helfi_grant_applications/global-styling
  - helfi_grant_applications/global-scripting
