settings:
  default_form_open_message: 'Tätä lomaketta ei ole vielä avattu lähetyksille.'
  default_submit_button_label: Skicka
  default_reset_button_label: Återställ
  default_delete_button_label: Radera
  default_form_confidential_message: 'Tämä lomake on luottamuksellinen. Sinun täytyy <a href="[site:login-url]/logout?destination=[current-page:url:relative]">kirjautua ulos</a> lähettääksesi se.'
  default_wizard_start_label: Från
  default_wizard_confirmation_label: Slutförd
  default_wizard_toggle_show_label: 'Näytä kaikki'
  default_wizard_toggle_hide_label: 'Piilota kaikki'
  default_preview_next_button_label: Förhandsgranska
  default_preview_label: Förhandsgranska
  default_draft_button_label: 'Spara utkast'
  default_draft_saved_message: 'Formulär sparat. Du kan återvända till detta formulär senare och fortsätta inmatningen.'
  default_confirmation_message: 'Lisätty uusi lähetys lomakkeelle [webform:title].'
  default_previous_submission_message: 'Du har redan skickat in detta formulär. <a href="#">Se ditt tidigare inlägg</a>.'
  dialog_options:
    narrow:
      title: Smal
    normal:
      title: Normal
    wide:
      title: Bred
element:
  empty_message: '-'
  default_more_title: Mer
test:
  types: ""
  names: "first_name:\r\n  - 'John'\r\n  - 'Paul'\r\n  - 'Ringo'\r\n  - 'George'\r\nlast_name:\r\n  - 'Lennon'\r\n  - 'McCartney'\r\n  - 'Starr'\r\n  - 'Harrison'\r\naddress:\r\n  - '10 Main Street'\r\n  - '11 Brook Alley Road. APT 1'\r\nzip:\r\n  - '11111'\r\n  - '12345'\r\n  - '12345-6789'\r\npostal_code:\r\n  - '11111'\r\n  - '12345'\r\n  - '12345-6789'\r\nphone:\r\n  - '123-456-7890'\r\n  - '098-765-4321'\r\nfax:\r\n  - '123-456-7890'\r\n  - '098-765-4321'\r\ncity:\r\n  - 'Springfield'\r\n  - 'Pleasantville'\r\n  - 'Hill Valley'\r\nurl:\r\n  - 'http://example.com'\r\n  - 'http://test.com'\r\ndefault:\r\n  - '12345'\r\n  - '23456'\r\n  - '23423'\r\n"
